export const vegeDishes = [
  { name: '芹菜炒香肠' },
  { name: '油麦菜' },
  { name: '炒杏鲍菇' },
  { name: '炒土豆丝' },
  { name: '麻婆豆腐' },
  { name: '西红柿鸡蛋' },
  { name: '炒菜花' },
  { name: '炝炒包菜' },
  { name: '炒茄子' },
  { name: '青椒鸡蛋' },
  { name: '白菜炖粉条' },
  { name: '凉拌黄瓜' },
  { name: '香菇油菜' },
  { name: '地三鲜' },
  { name: '豆泡炒青菜' },
  { name: '炒豆芽' },
  { name: '蚝油生菜' },
  { name: '蒜蓉金针菇' },
]

export const meatDishes = [
  { name: '鱼香肉丝' },
  { name: '宫保鸡丁' },
  { name: '干煸肉丝' },
  { name: '青椒肉丝' },
  { name: '辣子鸡' },
  { name: '青笋炒肉' },
  { name: '蒜薹炒肉' },
  { name: '回锅肉' },
  { name: '小炒肉' },
  { name: '酸豇豆肉沫' },
  { name: '小炒黄牛肉' },
  { name: '腊肉炒鱼腥草' },
]
