name: GitHub CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 先设置 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.0.0

      # 然后设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: 'pnpm'

      # 添加缓存
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Build
        run: |
          echo "开始构建"
          pnpm install
          pnpm build
          echo "构建完成"
          ls ${{ github.workspace }}/dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy to Tencent Cloud
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.TENCENT_HOST }}
          username: ${{ vars.TENCENT_USERNAME }}
          key: ${{ secrets.ID_ED25519_GITHUB_ACTIONS }}
          source: 'dist/'
          target: '/var/www/webpage/'
          strip_components: 1
          timeout: 120s
          overwrite: true
          debug: true # 添加调试模式
          port: 22 # 明确指定 SSH 端口
