name: GitHub CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 先设置 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.0.0

      # 然后设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: 'pnpm'

      # 添加缓存
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Build
        run: |
          echo "开始构建"
          pnpm install --frozen-lockfile
          pnpm build
          echo "构建完成"
          ls ${{ github.workspace }}/dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      # 新增构建产物校验
      - name: Validate Artifacts
        run: |
          if [ ! -d "dist" ]; then
            echo "构建产物不存在"
            exit 1
          fi
          echo "构建产物验证通过"

      - name: Deploy to Tencent Cloud
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.TENCENT_HOST }}
          username: ${{ vars.TENCENT_USERNAME }}
          key: ${{ secrets.ID_ED25519_GITHUB_ACTIONS }}
          source: 'dist/'
          target: '/var/www/hanzc.fun/'
          strip_components: 1
          timeout: 120s
          overwrite: true
          debug: true
          port: 22

      # 新增部署后健康检查
      - name: Health Check
        run: |
          echo "等待服务启动..."
          sleep 10
          curl -I https://hanzc.fun || echo "健康检查失败"
